# Generated by Django 3.1.4 on 2021-01-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=20)),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_school', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Backlogs',
            fields=[
                ('active_backlogs', models.IntegerField()),
                ('B_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backlogs1_app.student')),
            ],
        ),
    ]
